[package]
name = "voco-daemon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "voco-daemon"
path = "src/main.rs"

[dependencies]
voco-config = { path = "../voco-config" }
voco-ipc = { path = "../voco-ipc", features = ["server"] }
async-trait = "0.1"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
directories = { workspace = true }
anyhow = { workspace = true }
